spring:

  profiles:
    active: dev
    include: secret

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 300MB

  data:
    redis:
      port: 6379
      host: localhost
