# we can have the common settings in here
spring:
  # settings for profile
  profiles:
    default: dev  # if you want to have the environment of the develop server, then it should be dev not local

  # settings for multi part data such as image
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 300MB

