# jwt
jwt:
  secret: 63461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e38e3ff

# aws
cloud:
  aws:
    credentials:
      access-key: AKIA4NAJ3D2TCKQ4MKCQ
      secret-key: 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
    s3:
      bucket: umc-ticket-taka-bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

# oauth2
spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 2pgkwR4_xEP0Vu7f5dPr
            client-secret: 1bNVf7TRSA
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: email
            client-name: naver
          kakao:
            client-id: efa69149ca85e778e1e004537181ee58
            client-secret: p0SWeMcpHnNLjqe1oqO6rBH3asuvFAhK
            client-authentication-method: client_secret_post
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
          google:
            client-id: 213959457261-ecbk5blv232rrpmaauj46pgkkvj64h5s.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response