# we can have the specific settings in here for local server

server:
  port: 8081

# settings for database such as mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ticket # ticket is the name of my db not yours. so it can be different
    username: #[your username]
    password: #[your password]

# settings for spring jpa
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
