# we can have the specific settings in here for develop server
spring:
  config:
    activate:
      on-profile: dev # 환경이름설정

server:
  port: 8080

# below should be written with the aws RDS or something associated with develop environment